version: '3.1'
services:
  rmq:
    image: rabbitmq:3.11.11-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  mysql_user:
    image: mysql
    container_name: mysql_user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: support
      MYSQL_PASSWORD: support
      MYSQL_DATABASE: tickets
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_db_user:/var/lib/mysql
  mysql_support:
    image: mysql
    container_name: mysql_support
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: support
      MYSQL_PASSWORD: support
      MYSQL_DATABASE: tickets
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_db_support:/var/lib/mysql
